#!/bin/sh

_pkgver=4.3.5
source="https://github.com/pi-hole/pi-hole/archive/v$_pkgver.tar.gz"
dira="pi-hole-$_pkgver"
dirb="$dira.cust"

_ssc="/tmp/sedcontrol"

[[ -d $dira ]] && rm -r $dira
[[ -d $dirb ]] && rm -r $dirb

wget -q -nc $source
tar xf v$_pkgver.tar.gz
cp -a $dira $dirb

# the return of service management
sed -i "s|service \${resolver} restart|systemctl restart \${resolver}|w $_ssc" "$dirb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: the return of service management" && exit 1 ; fi

# setting up and securing pihole wrapper script
#sed -n "/debugFunc() {/w $_ssc" "$dirb"/pihole
#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 1" && exit 1 ; fi
#sed -i '/debugFunc() {/,+16d' "$dirb"/pihole

sed -n "/flushFunc() {/w $_ssc" "$dirb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 2" && exit 1 ; fi
sed -i '/flushFunc() {/,+4d' "$dirb"/pihole

sed -n "/versionFunc() {/w $_ssc" "$dirb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 3" && exit 1 ; fi
sed -i '/versionFunc() {/,+4d' "$dirb"/pihole

sed -n "/updatePiholeFunc() {/w $_ssc" "$dirb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 2" && exit 1 ; fi
sed -i '/updatePiholeFunc() {/,+5d' "$dirb"/pihole

sed -n "/reconfigurePiholeFunc() {/w $_ssc" "$dirb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 3" && exit 1 ; fi
sed -i '/reconfigurePiholeFunc() {/,+4d' "$dirb"/pihole

sed -n "/chronometerFunc() {/w $_ssc" "$dirb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 6" && exit 1 ; fi
sed -i '/chronometerFunc() {/,+4d' "$dirb"/pihole

sed -n "/uninstallFunc() {/w $_ssc" "$dirb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 4" && exit 1 ; fi
sed -i '/uninstallFunc() {/,+4d' "$dirb"/pihole

sed -n "/piholeCheckoutFunc() {/w $_ssc" "$dirb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 5" && exit 1 ; fi
sed -i '/piholeCheckoutFunc() {/,+22d' "$dirb"/pihole

sed -n "/tricorderFunc() {/w $_ssc" "$dirb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 6" && exit 1 ; fi
sed -i '/tricorderFunc() {/,+30d' "$dirb"/pihole

sed -n "/\"\-[r,c,v,up]/w $_ssc" "$dirb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 7" && exit 1 ; fi
sed -i '/\"\-[r,c,v,up]/d' "$dirb"/pihole

sed -n "/^  \-[r,t,l,f,c,v],/w $_ssc" "$dirb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 11" && exit 1 ; fi
sed -i '/^  \-[r,t,l,f,c,v],/d' "$dirb"/pihole

sed -n "/^  \-up,/w $_ssc" "$dirb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 13" && exit 1 ; fi
sed -i '/^  \-up,/d' "$dirb"/pihole

sed -n "/^  \-a,/w $_ssc" "$dirb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 14" && exit 1 ; fi
sed -i '/^  \-a,/,+1d' "$dirb"/pihole

sed -n "/uninstall/w $_ssc" "$dirb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 11" && exit 1 ; fi
sed -i '/uninstall/d' "$dirb"/pihole

sed -i "s|^  checkout.*$|\";|w $_ssc" "$dirb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 12" && exit 1 ; fi

sed -n "/checkout/w $_ssc" "$dirb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 13" && exit 1 ; fi
sed -i '/checkout/d' "$dirb"/pihole

sed -n "/tricorder/w $_ssc" "$dirb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 14" && exit 1 ; fi
sed -i '/tricorder/d' "$dirb"/pihole

sed -n "/updatechecker/w $_ssc" "$dirb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 19" && exit 1 ; fi
sed -i '/updatechecker/d' "$dirb"/pihole

# -----------------

# setup gravity.sh
sed -i "s|/usr/local/bin/|/usr/bin/|w $_ssc" "$dirb"/gravity.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setup gravity.sh 1" && exit 1 ; fi

# setup pihole
sed -i "s|/usr/local/bin|/usr/bin|w $_ssc" "$dirb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setup pihole 1" && exit 1 ; fi

# -----------------

# setting up and securing webpage.sh script
sed -n "/SetWebPassword() {/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 1" && exit 1 ; fi
sed -i '/SetWebPassword() {/,+44d' "$dirb"/advanced/Scripts/webpage.sh

sed -n "/SetTemperatureUnit() {/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 2" && exit 1 ; fi
sed -i '/SetTemperatureUnit() {/,+3d' "$dirb"/advanced/Scripts/webpage.sh

sed -n "/SetExcludeDomains() {/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 3" && exit 1 ; fi
sed -i '/SetExcludeDomains() {/,+3d' "$dirb"/advanced/Scripts/webpage.sh

sed -n "/SetExcludeClients() {/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 4" && exit 1 ; fi
sed -i '/SetExcludeClients() {/,+3d' "$dirb"/advanced/Scripts/webpage.sh

sed -n "/EnableDHCP() {/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 5" && exit 1 ; fi
sed -i '/EnableDHCP() {/,+26d' "$dirb"/advanced/Scripts/webpage.sh

sed -n "/DisableDHCP() {/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 6" && exit 1 ; fi
sed -i '/DisableDHCP() {/,+11d' "$dirb"/advanced/Scripts/webpage.sh

sed -n "/SetWebUILayout() {/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 7" && exit 1 ; fi
sed -i '/SetWebUILayout() {/,+3d' "$dirb"/advanced/Scripts/webpage.sh

sed -n "/SetPrivacyMode() {/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 8" && exit 1 ; fi
sed -i '/SetPrivacyMode() {/,+7d' "$dirb"/advanced/Scripts/webpage.sh

sed -n "/\"\-[p,c,f,k]/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 9" && exit 1 ; fi
sed -i '/\"\-[p,c,f,k]/d' "$dirb"/advanced/Scripts/webpage.sh

sed -n "/  \-[p,c,f,k]/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 9" && exit 1 ; fi
sed -i '/  \-[p,c,f,k]/d' "$dirb"/advanced/Scripts/webpage.sh

sed -n "/\"setexcludedomains/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 10" && exit 1 ; fi
sed -i '/\"setexcludedomains/d' "$dirb"/advanced/Scripts/webpage.sh
sed -n "/\"setexcludeclients/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 11" && exit 1 ; fi
sed -i '/\"setexcludeclients/d' "$dirb"/advanced/Scripts/webpage.sh
sed -n "/\"enabledhcp/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 12" && exit 1 ; fi
sed -i '/\"enabledhcp/d' "$dirb"/advanced/Scripts/webpage.sh
sed -n "/\"disabledhcp/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 13" && exit 1 ; fi
sed -i '/\"disabledhcp/d' "$dirb"/advanced/Scripts/webpage.sh
sed -n "/\"layout/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 14" && exit 1 ; fi
sed -i '/\"layout/d' "$dirb"/advanced/Scripts/webpage.sh
sed -n "/\"privacymode/w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 15" && exit 1 ; fi
sed -i '/\"privacymode/d' "$dirb"/advanced/Scripts/webpage.sh

sed -i "s|/usr/local/bin|/usr/bin|w $_ssc" "$dirb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 16" && exit 1 ; fi

# -----------------

# pi-hole dnsmasq config file include ready
echo "conf-dir=/etc/dnsmasq.d/,*.conf" >> "$dirb"/advanced/dnsmasq.conf.original

# adlists.default is gone and adlists.list is populated by install script
# from basic-install.sh -- function chooseBlocklists()
cat <<EOF > "$dirb"/adlists.list
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://mirror1.malwaredomains.com/files/justdomains
http://sysctl.org/cameleon/hosts
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
https://hosts-file.net/ad_servers.txt
EOF

diff -uprN $dira $dirb > arch-server-core-$_pkgver.patch
git add arch-server-core-$_pkgver.patch
git add patchgen
