#!/bin/sh

_pkgver=5.5
source_core="https://github.com/pi-hole/pi-hole/archive/v$_pkgver.tar.gz"
dircorea="pi-hole-$_pkgver"
dircoreb="$dircorea.cust"

_ssc="/tmp/sedcontrol"

[[ -d $dircorea ]] && rm -r $dircorea
[[ -d $dircoreb ]] && rm -r $dircoreb

wget -q -nc -O pihole-$_pkgver.tar.gz $source_core
tar xf pihole-$_pkgver.tar.gz
cp -a $dircorea $dircoreb

# the return of service management
sed -i "s|service pihole-FTL restart|systemctl restart pihole-FTL|w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: the return of service management" && exit 1 ; fi

# setting up and securing pihole wrapper script
#sed -n "/debugFunc() {/w $_ssc" "$dircoreb"/pihole
#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 1" && exit 1 ; fi
#sed -i '/debugFunc() {/,+16d' "$dircoreb"/pihole

sed -n "/flushFunc() {/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 2" && exit 1 ; fi
sed -i '/flushFunc() {/,+4d' "$dircoreb"/pihole

sed -n "/versionFunc() {/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 3" && exit 1 ; fi
sed -i '/versionFunc() {/,+4d' "$dircoreb"/pihole

sed -n "/updatePiholeFunc() {/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 2" && exit 1 ; fi
sed -i '/updatePiholeFunc() {/,+5d' "$dircoreb"/pihole

sed -n "/reconfigurePiholeFunc() {/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 3" && exit 1 ; fi
sed -i '/reconfigurePiholeFunc() {/,+4d' "$dircoreb"/pihole

sed -n "/chronometerFunc() {/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 6" && exit 1 ; fi
sed -i '/chronometerFunc() {/,+4d' "$dircoreb"/pihole

sed -n "/uninstallFunc() {/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 4" && exit 1 ; fi
sed -i '/uninstallFunc() {/,+4d' "$dircoreb"/pihole

sed -n "/piholeCheckoutFunc() {/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 5" && exit 1 ; fi
sed -i '/piholeCheckoutFunc() {/,+22d' "$dircoreb"/pihole

sed -n "/tricorderFunc() {/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 6" && exit 1 ; fi
sed -i '/tricorderFunc() {/,+20d' "$dircoreb"/pihole

sed -n "/\"\-[r,c,v,up]/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 7" && exit 1 ; fi
sed -i '/\"\-[r,c,v,up]/d' "$dircoreb"/pihole

sed -n "/^  \-[r,t,l,f,c,v],/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 11" && exit 1 ; fi
sed -i '/^  \-[r,t,l,f,c,v],/d' "$dircoreb"/pihole

sed -n "/^  \-up,/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 13" && exit 1 ; fi
sed -i '/^  \-up,/d' "$dircoreb"/pihole

sed -n "/^  \-a,/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 14" && exit 1 ; fi
sed -i '/^  \-a,/,+1d' "$dircoreb"/pihole

sed -n "/uninstall/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 11" && exit 1 ; fi
sed -i '/uninstall/d' "$dircoreb"/pihole

sed -n "/^  checkout/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 12" && exit 1 ; fi
sed -i '/^  checkout/,+1d' "$dircoreb"/pihole

sed -n "/^  \"checkout/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 13" && exit 1 ; fi
sed -i '/^  \"checkout/d' "$dircoreb"/pihole

sed -n "/tricorder/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 14" && exit 1 ; fi
sed -i '/tricorder/d' "$dircoreb"/pihole

sed -n "/updatechecker/w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing pihole wrapper script 19" && exit 1 ; fi
sed -i '/updatechecker/d' "$dircoreb"/pihole

# -----------------

# setup gravity.sh
sed -i "s|/usr/local/bin/|/usr/bin/|w $_ssc" "$dircoreb"/gravity.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setup gravity.sh 1" && exit 1 ; fi
sed -i "s|source \"/etc/.pihole/advanced/Scripts/database_migration/gravity-db.sh\"|source \"/opt/pihole/database_migration/gravity-db.sh\"|w $_ssc" "$dircoreb"/gravity.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setup gravity.sh 2" && exit 1 ; fi
sed -i "s|\${piholeGitDir}/advanced/Templates/gravity|/opt/pihole/gravity|w $_ssc" "$dircoreb"/gravity.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setup gravity.sh 3" && exit 1 ; fi

# setup gravity.db.sh
sed -i "s|/etc/.pihole/advanced/Scripts/database_migration/gravity|/opt/pihole/database_migration/gravity|w $_ssc" "$dircoreb"/advanced/Scripts/database_migration/gravity-db.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setup gravity.sh 1" && exit 1 ; fi

# setup pihole
sed -i "s|/usr/local/bin|/usr/bin|w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setup pihole 1" && exit 1 ; fi
sed -i "s|/run/pihole-FTL.pid|/run/pihole-ftl/pihole-FTL.pid|w $_ssc" "$dircoreb"/pihole
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setup pihole 2" && exit 1 ; fi

# -----------------

# change FTL port file location to chronometer.sh
sed -i "s|\${PI_HOLE_FILES_DIR}/automated install/basic-install.sh|/opt/pihole/basic-install.sh|w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: change FTL port file location to chronometer.sh" && exit 1 ; fi

# -----------------

# setting up and securing webpage.sh script
sed -n "/SetWebPassword() {/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 1" && exit 1 ; fi
sed -i '/SetWebPassword() {/,+44d' "$dircoreb"/advanced/Scripts/webpage.sh

sed -n "/SetTemperatureUnit() {/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 2" && exit 1 ; fi
sed -i '/SetTemperatureUnit() {/,+3d' "$dircoreb"/advanced/Scripts/webpage.sh

sed -n "/SetExcludeDomains() {/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 3" && exit 1 ; fi
sed -i '/SetExcludeDomains() {/,+3d' "$dircoreb"/advanced/Scripts/webpage.sh

sed -n "/SetExcludeClients() {/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 4" && exit 1 ; fi
sed -i '/SetExcludeClients() {/,+3d' "$dircoreb"/advanced/Scripts/webpage.sh

sed -n "/EnableDHCP() {/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 5" && exit 1 ; fi
sed -i '/EnableDHCP() {/,+26d' "$dircoreb"/advanced/Scripts/webpage.sh

sed -n "/DisableDHCP() {/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 6" && exit 1 ; fi
sed -i '/DisableDHCP() {/,+11d' "$dircoreb"/advanced/Scripts/webpage.sh

sed -n "/SetWebUILayout() {/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 7" && exit 1 ; fi
sed -i '/SetWebUILayout() {/,+3d' "$dircoreb"/advanced/Scripts/webpage.sh

sed -n "/SetPrivacyMode() {/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 8" && exit 1 ; fi
sed -i '/SetPrivacyMode() {/,+7d' "$dircoreb"/advanced/Scripts/webpage.sh

sed -n "/\"\-[p,c,f,k]/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 9" && exit 1 ; fi
sed -i '/\"\-[p,c,f,k]/d' "$dircoreb"/advanced/Scripts/webpage.sh

sed -n "/  \-[p,c,f,k]/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 9" && exit 1 ; fi
sed -i '/  \-[p,c,f,k]/d' "$dircoreb"/advanced/Scripts/webpage.sh

sed -n "/\"setexcludedomains/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 10" && exit 1 ; fi
sed -i '/\"setexcludedomains/d' "$dircoreb"/advanced/Scripts/webpage.sh
sed -n "/\"setexcludeclients/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 11" && exit 1 ; fi
sed -i '/\"setexcludeclients/d' "$dircoreb"/advanced/Scripts/webpage.sh
sed -n "/\"enabledhcp/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 12" && exit 1 ; fi
sed -i '/\"enabledhcp/d' "$dircoreb"/advanced/Scripts/webpage.sh
sed -n "/\"disabledhcp/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 13" && exit 1 ; fi
sed -i '/\"disabledhcp/d' "$dircoreb"/advanced/Scripts/webpage.sh
sed -n "/\"layout/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 14" && exit 1 ; fi
sed -i '/\"layout/d' "$dircoreb"/advanced/Scripts/webpage.sh
sed -n "/\"privacymode/w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 15" && exit 1 ; fi
sed -i '/\"privacymode/d' "$dircoreb"/advanced/Scripts/webpage.sh

#sed -i "s|/usr/local/bin|/usr/bin|w $_ssc" "$dircoreb"/advanced/Scripts/webpage.sh
#if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: setting up and securing webpage.sh script 16" && exit 1 ; fi

# -----------------

# pi-hole dnsmasq config file include ready
echo "conf-dir=/etc/dnsmasq.d/,*.conf" >> "$dircoreb"/advanced/dnsmasq.conf.original

# adlists.default is gone and adlists.list is populated by install script
# from basic-install.sh -- function chooseBlocklists()
cat <<EOF > "$dircoreb"/adlists.list
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://mirror1.malwaredomains.com/files/justdomains
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
EOF

diff -uprN $dircorea $dircoreb > arch-server-core-$_pkgver.patch
git add arch-server-core-$_pkgver.patch
git add patchgen
